### PR TITLE
cosmetic and fix backup info, #30, #32, #34

### LINKED ISSUE #30: Broken sync
Hey, I think there last commit broke the db sync.

Should be:
```
except:
    print("Corrupted/Incomplete Backup!");
    continue

wa_backup.fetch_all(backup, cksums)
````

Instead of:
```
except:
    print("Corrupted/Incomplete Backup!");
    continue

    wa_backup.fetch_all(backup, cksums)
````

### LINKED ISSUE #32: can't download files
after i run sync command if shows this and stops 
Backup clients/wa/backups/xxxxxxxxx (588MiB):

### PR DESCRIPTION
**Pull request by Alcazer**

### CODE REVIEW

**Comment by elmannani** [comment]
after i run sync command if shows this and stops
Backup clients/wa/backups/xxxxxxxxx (588MiB):

**Comment by Alcazer** [comment]
@YuriCosta Can you merge request?

**Comment by Alcazer** [comment]
@YuriCosta please merge pull request

**Comment by Alcazer** [comment]
@YuriCosta please merge pull request

**Comment by Alcazer** [comment]
@YuriCosta please merge pull request

**Review by YuriCosta — APPROVED** [review]

**Pull request merged**
