### PR TITLE
Update settings.cfg

### PR DESCRIPTION
**Pull request by xiaoveiti**
added description for cellnumber

### CODE REVIEW

**Comment by Tebeye** [comment]
I am getting Auth error, Probably my device id is wrong.
How can we get device ID. Even I wrote my own Android program everytime the ID changes.

**Comment by nicolabeghin** [comment]
Following. Experiencing the same issue, get 403 forbidden at first step when authenticating through POST to https://android.clients.google.com/auth

image

**Comment by YuriCosta** [comment]
> Following. Experiencing the same issue, get 403 forbidden at first step when authenticating through POST to https://android.clients.google.com/auth
> 
> @YuriCosta if you have any hint, debugging but something must have changed google-wise?
> 
> image

Are you providing access by UnlockDisplayCaptcha? You must go to the site and enable the temporary security access and run the script after. I've tested this morning and it was working fine.

**Comment by Tebeye** [comment]
@YuriCosta I can not use the program on Android 10. Are you sure it is working? How did you get your Device ID correctly, I am looking in GoogleDrive Whatsapp Backup.

**Comment by nicolabeghin** [comment]
> Are you providing access by UnlockDisplayCaptcha? You must go to the site and enable the temporary security access and run the script after. I've tested this morning and it was working fine.
just tried, unfortunately no luck, same output :/

image

**Comment by nicolabeghin** [comment]
If useful, here's the Dockerfile to reproduce exactly the same environment (usually try to avoid polluting local system when using Python)

    FROM python:3.8-slim-buster
    
    # Keeps Python from generating .pyc files in the container
    ENV PYTHONDONTWRITEBYTECODE=1
    
    # Turns off buffering for easier container logging
    ENV PYTHONUNBUFFERED=1
    
    # Install pip requirements
    COPY requirements.txt .
    RUN python -m pip install -r requirements.txt
    
    WORKDIR /app
    COPY . /app
    
    RUN useradd appuser && chown -R appuser /app
    USER appuser
    
    CMD ["python", "WhatsAppGDExtract.py", "-info"]

**Comment by Tebeye** [comment]
@nicolabeghin Sir do you have any idea how can I get my device ID. After Android 10 patch. Each time you've installed an application the unique id changes.

Am I looking right place?
[https://hizliresim.com/WOi16L](url)

**Comment by YuriCosta** [comment]
@nicolabeghin and @Tebeye I'm just using the default device ID (108204F52113BE44), I think the script builds this automatically.
I've just tested the script, it'd normal, make sure the DisplayUnlockCaptcha is running on the account you're trying to retrieve your data.

**Comment by Tebeye** [comment]
@YuriCosta @nicolabeghin  I closed the DisplayUnlockCaptcha feature for my account. But probably my device id is not correct. Could you please tell me the steps to get the device id?

**Comment by YuriCosta** [comment]
@Tebeye I don't think even with the right device ID it will work but you can try, in the play store there's a couple of apps that show your device ID, just search "device id".

**Comment by Bubblebug17** [comment]
I've faced the same problem a few days ago when I made a clean install of this repo and its dependencies. And I found that the problems is in Resquest library, apparently there is a bug related with its last version.
So I solved the '`Error=BadAuthentication'` problem  by installing:  **requests 2.21.0**.
Command : `pip install requests==2.21.0`.

**Comment by nicolabeghin** [comment]
@Bubblebug17 super!!! it works now, thanks a lot, great catch!

**Comment by YuriCosta** [comment]
> I've faced the same problem a few days ago when I made a clean install of this repo and its dependencies. And I found that the problem is in Resquest library, apparently there is a bug related with its last version.
> So I solved the '`Error=BadAuthentication'` problem by installing: **requests 2.21.0**.
> Command : `pip install requests==2.21.0`.

That explains why I don't have a problem, I was using an old version of requests. Ty

**Review by YuriCosta — APPROVED** [review]

**Comment by YuriCosta** [comment]
I created a issues tab so we can discuss there for now on.

**Pull request merged**
